let products = [
    // Sala de Estar
    {
        id: 1,
        nome: "Sofá 3 Lugares Cinza",
        imagem: "./images/sofa-cinza.jpg",
        quantidade: 5,
        categoria: "sala",
        valor: 1299.99,
    },
    {
        id: 2,
        nome: "Mesa de Centro Madeira",
        imagem: "./images/mesa-centro-madeira.png",
        quantidade: 8,
        categoria: "sala",
        valor: 599.99,
    },
    {
        id: 3,
        nome: "Poltrona Reclinável Couro",
        imagem: "./images/poltrona-reclinavel.png",
        quantidade: 3,
        categoria: "sala",
        valor: 899.99,
    },
    {
        id: 4,
        nome: "Rack para TV 55 polegadas",
        imagem: "./images/rack-tv.jpg",
        quantidade: 12,
        categoria: "sala",
        valor: 449.99,
    },
    {
        id: 5,
        nome: "Estante Livros 5 Prateleiras",
        imagem: "./images/estante-livros.jpg",
        quantidade: 6,
        categoria: "sala",
        valor: 329.99,
    },
    {
        id: 6,
        nome: "Sofá Canto L Bege",
        imagem: "./images/sofa-canto.jpg",
        quantidade: 2,
        categoria: "sala",
        valor: 1899.99,
    },
    {
        id: 7,
        nome: "Mesa Lateral Vidro",
        imagem: "./images/mesa-lateral.jpg",
        quantidade: 15,
        categoria: "sala",
        valor: 199.99,
    },
    {
        id: 8,
        nome: "Puff Redondo Azul",
        imagem: "./images/puff-redondo.jpeg",
        quantidade: 20,
        categoria: "sala",
        valor: 149.99,
    },
    {
        id: 9,
        nome: "Aparador Sala Branco",
        imagem: "./images/aparador-sala.jpeg",
        quantidade: 4,
        categoria: "sala",
        valor: 699.99,
    },
    {
        id: 10,
        nome: "Luminária de Chão LED",
        imagem: "./images/luminaria-chao.jpeg",
        quantidade: 0,
        categoria: "sala",
        valor: 299.99,
    },

    // Quarto
    {
        id: 11,
        nome: "Cama Casal Box Molas",
        imagem: "./images/cama-casal.jpeg",
        quantidade: 7,
        categoria: "quarto",
        valor: 1199.99,
    },
    {
        id: 12,
        nome: "Guarda-Roupa 6 Portas",
        imagem: "./images/guarda-roupa.jpeg",
        quantidade: 3,
        categoria: "quarto",
        valor: 1599.99,
    },
    {
        id: 13,
        nome: "Cômoda 4 Gavetas Branca",
        imagem: "./images/comoda-branca.jpeg",
        quantidade: 9,
        categoria: "quarto",
        valor: 399.99,
    },
    {
        id: 14,
        nome: "Criado-Mudo Suspenso",
        imagem: "./images/criado-mudo.jpeg",
        quantidade: 14,
        categoria: "quarto",
        valor: 179.99,
    },
    {
        id: 15,
        nome: "Penteadeira com Espelho",
        imagem: "./images/penteadeira.jpeg",
        quantidade: 5,
        categoria: "quarto",
        valor: 549.99,
    },
    {
        id: 16,
        nome: "Cama Solteiro Infantil",
        imagem: "./images/cama-solteiro.jpeg",
        quantidade: 8,
        categoria: "quarto",
        valor: 699.99,
    },
    {
        id: 17,
        nome: "Beliche Madeira Maciça",
        imagem: "./images/beliche-madeira.jpeg",
        quantidade: 2,
        categoria: "quarto",
        valor: 1299.99,
    },
    {
        id: 18,
        nome: "Escrivaninha Home Office",
        imagem: "./images/escrivaninha.jpeg",
        quantidade: 11,
        categoria: "quarto",
        valor: 449.99,
    },
    {
        id: 19,
        nome: "Poltrona Leitura Tecido",
        imagem: "./images/poltrona-leitura.jpeg",
        quantidade: 6,
        categoria: "quarto",
        valor: 599.99,
    },
    {
        id: 20,
        nome: "Espelho Grande Moldura",
        imagem: "./images/espelho-grande.jpeg",
        quantidade: 0,
        categoria: "quarto",
        valor: 299.99,
    },

    // Cozinha
    {
        id: 21,
        nome: "Mesa Jantar 6 Lugares",
        imagem: "./images/mesa-seis-lugares.jpeg",
        quantidade: 4,
        categoria: "cozinha",
        valor: 899.99,
    },
    {
        id: 22,
        nome: "Cadeiras Jantar Kit 4un",
        imagem: "./images/cadeiras.jpeg",
        quantidade: 12,
        categoria: "cozinha",
        valor: 399.99,
    },
    {
        id: 23,
        nome: "Armário Cozinha Aéreo",
        imagem: "./images/armario-cozinha.jpeg",
        quantidade: 7,
        categoria: "cozinha",
        valor: 649.99,
    },
    {
        id: 24,
        nome: "Balcão Pia Granito",
        imagem: "./images/balcao-pia-granito.jpeg",
        quantidade: 3,
        categoria: "cozinha",
        valor: 1199.99,
    },
    {
        id: 25,
        nome: "Banquetas Bar Altura",
        imagem: "./images/banquetas-bar.jpeg",
        quantidade: 16,
        categoria: "cozinha",
        valor: 199.99,
    },
    {
        id: 26,
        nome: "Fruteira Madeira Bambú",
        imagem: "./images/fruteira.jpeg",
        quantidade: 25,
        categoria: "cozinha",
        valor: 79.99,
    },
    {
        id: 27,
        nome: "Carrinho Bar Rodízios",
        imagem: "./images/carrinho-bar.jpeg",
        quantidade: 8,
        categoria: "cozinha",
        valor: 349.99,
    },
    {
        id: 28,
        nome: "Mesa Dobrável Parede",
        imagem: "./images/mesa-dobravel.jpeg",
        quantidade: 10,
        categoria: "cozinha",
        valor: 249.99,
    },
    {
        id: 29,
        nome: "Prateleira Temperos Inox",
        imagem: "./images/prateleira-temperos.jpeg",
        quantidade: 18,
        categoria: "cozinha",
        valor: 129.99,
    },
    {
        id: 30,
        nome: "Lixeira Inox Pedal",
        imagem: "./images/lixeira-inox-pedal.jpeg",
        quantidade: 0,
        categoria: "cozinha",
        valor: 159.99,
    },

    // Produtos adicionais para completar 30+
    {
        id: 31,
        nome: "Tapete Sala Geométrico",
        imagem: "./images/tapete-sala-geometrico.jpeg",
        quantidade: 22,
        categoria: "sala",
        valor: 199.99,
    },
    {
        id: 32,
        nome: "Almofadas Decorativas Kit",
        imagem: "./images/almofadas.jpeg",
        quantidade: 30,
        categoria: "sala",
        valor: 89.99,
    },
    {
        id: 33,
        nome: "Cortina Blackout Quarto",
        imagem: "./images/cortina.jpeg",
        quantidade: 15,
        categoria: "quarto",
        valor: 149.99,
    },
    {
        id: 34,
        nome: "Organizador Gavetas",
        imagem: "./images/organizador.jpeg",
        quantidade: 40,
        categoria: "quarto",
        valor: 49.99,
    },
    {
        id: 35,
        nome: "Tábua Corte Madeira",
        imagem: "./images/tabua-corte-madeira.jpeg",
        quantidade: 35,
        categoria: "cozinha",
        valor: 39.99,
    },
]

export default products
